export default {
  login: 'TraderCodes',
  id: 85665271,
  node_id: 'MDQ6VXNlcjg1NjY1Mjcx',
  avatar_url: 'https://avatars.githubusercontent.com/u/85665271?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/TraderCodes',
  html_url: 'https://github.com/TraderCodes',
  followers_url: 'https://api.github.com/users/TraderCodes/followers',
  following_url:
    'https://api.github.com/users/TraderCodes/following{/other_user}',
  gists_url: 'https://api.github.com/users/TraderCodes/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/TraderCodes/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/TraderCodes/subscriptions',
  organizations_url: 'https://api.github.com/users/TraderCodes/orgs',
  repos_url: 'https://api.github.com/users/TraderCodes/repos',
  events_url: 'https://api.github.com/users/TraderCodes/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/TraderCodes/received_events',
  type: 'User',
  site_admin: false,
  name: 'TraderCodes',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: 'Doing my best to learn as much as i can',
  twitter_username: 'TraderCodes',
  public_repos: 35,
  public_gists: 0,
  followers: 1,
  following: 4,
  created_at: '2021-06-10T05:48:12Z',
  updated_at: '2022-05-19T23:35:37Z',
};

